[workspace]

members = [
  "common",
  "dmntk",
  "evaluator",
  "examples",
  "feel",
  "feel-grammar",
  "feel-evaluator",
  "feel-number",
  "feel-parser",
  "gendoc",
  "model",
  "model-evaluator",
  "recognizer",
  "server",
  "workspace"
]

[workspace.package]
version = "0.0.47"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
dmntk-common = "=0.0.47"
dmntk-evaluator = "=0.0.47"
dmntk-examples = "=0.0.47"
dmntk-feel = "=0.0.47"
dmntk-feel-evaluator = "=0.0.47"
dmntk-feel-grammar = "=0.0.47"
dmntk-feel-number = "=0.0.47"
dmntk-feel-parser = "=0.0.47"
dmntk-gendoc = "=0.0.47"
dmntk-model = "=0.0.47"
dmntk-model-evaluator = "=0.0.47"
dmntk-recognizer = "=0.0.47"
dmntk-server = "=0.0.47"
dmntk-workspace = "=0.0.47"
serde = { version = "1.0.147", features = ["derive"] }
serde_derive = "1.0.147"
serde_yaml = "0.9.14"
serde_json = "1.0.88"