[workspace]

members = [
  "common",
  "dmntk",
  "evaluator",
  "examples",
  "feel",
  "feel-grammar",
  "feel-evaluator",
  "feel-number",
  "feel-parser",
  "feel-temporal",
  "gendoc",
  "model",
  "model-evaluator",
  "recognizer",
  "server",
  "workspace"
]

[workspace.package]
version = "0.1.0-dev"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4.2.1"
base64 = "0.21.0"
dmntk-common = { path = "common" }
dmntk-evaluator = { path = "evaluator" }
dmntk-examples = { path = "examples" }
dmntk-feel = { path = "feel" }
dmntk-feel-evaluator = { path = "feel-evaluator" }
dmntk-feel-grammar = { path = "feel-grammar" }
dmntk-feel-number = { path = "feel-number" }
dmntk-feel-parser = { path = "feel-parser" }
dmntk-feel-temporal = { path = "feel-temporal" }
dmntk-gendoc = { path = "gendoc" }
dmntk-model = { path = "model" }
dmntk-model-evaluator = { path = "model-evaluator" }
dmntk-recognizer = { path = "recognizer" }
dmntk-server = { path = "server" }
dmntk-workspace = { path = "workspace" }
serde = { version = "1.0.150" }
serde_derive = "1.0.150"
serde_json = "1.0.89"