[workspace]

members = [
  "common",
  "dmntk",
  "evaluator",
  "examples",
  "feel",
  "feel-grammar",
  "feel-evaluator",
  "feel-number",
  "feel-parser",
  "feel-temporal",
  "gendoc",
  "model",
  "model-evaluator",
  "recognizer",
  "server",
  "workspace"
]

[workspace.package]
version = "0.0.50"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[workspace.dependencies]
dmntk-common = "0.0.50"
dmntk-evaluator = "0.0.50"
dmntk-examples = "0.0.50"
dmntk-feel = "0.0.50"
dmntk-feel-evaluator = "0.0.50"
dmntk-feel-grammar = "0.0.50"
dmntk-feel-number = "0.0.50"
dmntk-feel-parser = "0.0.50"
dmntk-feel-temporal = "0.0.50"
dmntk-gendoc = "0.0.50"
dmntk-model = "0.0.50"
dmntk-model-evaluator = "0.0.50"
dmntk-recognizer = "0.0.50"
dmntk-server = "0.0.50"
dmntk-workspace = "0.0.50"
serde = { version = "1.0.150" }
serde_derive = "1.0.150"
serde_json = "1.0.89"