version: '3'

silent: true

tasks:

  bench:
    desc: Runs all benchmarks
    cmds:
      - cmd: cargo bench -q | grep 'bench'

  benchmarks:
    desc: Runs all compliance benchmarks
    cmds:
      - cmd: cargo bench -q compliance | grep 'bench' > benchmarks.txt

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo build

  build-tck:
    desc: Builds in debug mode with TCK feature
    cmds:
      - cmd: cargo build --features=tck

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  cov:
    desc: Runs code coverage using grcov
    cmds:
      - cmd: ./coverage.sh

  cov-common:
    desc: Runs code coverage using grcov for dmntk-common
    cmds:
      - cmd: ./coverage.sh dmntk-common

  cov-feel:
    desc: Runs code coverage using grcov for dmntk-feel
    cmds:
      - cmd: ./coverage.sh dmntk-feel

  cov-feel-parser:
    desc: Runs code coverage using grcov for dmntk-feel-parser
    cmds:
      - cmd: ./coverage.sh dmntk-feel-parser

  cov-feel-evaluator:
    desc: Runs code coverage using grcov for dmntk-feel-evaluator
    cmds:
      - cmd: ./coverage.sh dmntk-feel-evaluator

  tcov:
    desc: Runs code coverage using tarpaulin
    cmds:
      - cmd: cargo tarpaulin {{.CLI_ARGS}} --out Html --output-dir ./target/tarpaulin

  tcov-open:
    desc: Runs code coverage using tarpaulin and opens the coverage report in browser
    cmds:
      - cmd: cargo tarpaulin {{.CLI_ARGS}} --out Html --output-dir ./target/tarpaulin
      - cmd: echo -e '#!/usr/bin/env bash\n\nfirefox ./target/tarpaulin/tarpaulin-report.html &' > ./target/tarpaulin/open-report.sh
      - cmd: chmod +x ./target/tarpaulin/open-report.sh
      - cmd: ./target/tarpaulin/open-report.sh

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc-priv:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo doc --no-deps --open --document-private-items

  install:
    desc: Builds and installs release version
    cmds:
      - cmd: cargo uninstall dmntk > /dev/null 2>&1
        ignore_error: true
      - cmd: rm ~/.cargo/bin/dmntl > /dev/null 2>&1
        ignore_error: true
      - cmd: cargo build --release
      - cmd: cp ./target/release/dmntk ~/.cargo/bin/

  musl:
    desc: Builds the Linux MUSL target
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-musl

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable build --release

  run:
    desc: Runs the server in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable run --release -- run -p 12000

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo test

  testq:
    desc: Runs tests in debug and quiet mode
    cmds:
      - cmd: cargo test -q

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo clippy --all-targets

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo fmt
