version: '3'

silent: true

tasks:

  bench:
    desc: Runs all benchmarks
    cmds:
      - cmd: cargo bench -q | grep 'bench'

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  cov-open:
    desc: Runs code coverage and opens it in browser
    cmds:
      - cmd: cargo tarpaulin {{.CLI_ARGS}} --out Html --output-dir ./target/tarpaulin
      - cmd: echo -e '#!/usr/bin/env bash\n\nfirefox ./target/tarpaulin/tarpaulin-report.html &' > ./target/tarpaulin/open-report.sh
      - cmd: chmod +x ./target/tarpaulin/open-report.sh
      - cmd: ./target/tarpaulin/open-report.sh

  cov:
    desc: Runs code coverage
    cmds:
      - cmd: cargo tarpaulin {{.CLI_ARGS}} --out Html --output-dir ./target/tarpaulin

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo doc --no-deps --open

  doc-priv:
    desc: Generates documentation
    cmds:
      - cmd: cargo doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo doc --no-deps --open --document-private-items

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable build --release

  run:
    desc: Runs the server in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable run --release -- run -p 12000

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo test

  testq:
    desc: Runs tests in debug and quiet mode
    cmds:
      - cmd: cargo test -q

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo clippy --all-targets

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo fmt
