version: '3'

silent: true

tasks:

  bench:
    desc: Runs all benchmarks
    cmds:
      - cmd: cargo +nightly bench -q | grep 'bench'

  benchmarks:
    desc: Runs all compatibility benchmarks
    cmds:
      - cmd: cargo +nightly bench -q compatibility | grep 'bench' > benchmarks.txt

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build --workspace

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --workspace --all-targets

  cov:
    desc: Runs code coverage using grcov
    cmds:
      - cmd: ./coverage.sh

  cov-common:
    desc: Runs code coverage using grcov for dmntk-common
    cmds:
      - cmd: ./coverage.sh dmntk-common

  cov-feel-number:
    desc: Runs code coverage using grcov for dmntk-feel-number
    cmds:
      - cmd: ./coverage.sh dmntk-feel-number

  cov-feel:
    desc: Runs code coverage using grcov for dmntk-feel
    cmds:
      - cmd: ./coverage.sh dmntk-feel

  cov-feel-parser:
    desc: Runs code coverage using grcov for dmntk-feel-parser
    cmds:
      - cmd: ./coverage.sh dmntk-feel-parser

  cov-feel-evaluator:
    desc: Runs code coverage using grcov for dmntk-feel-evaluator
    cmds:
      - cmd: ./coverage.sh dmntk-feel-evaluator

  cov-feel-grammar:
    desc: Runs code coverage using grcov for dmntk-feel-grammar
    cmds:
      - cmd: ./coverage.sh dmntk-feel-grammar

  cov-feel-temporal:
    desc: Runs code coverage using grcov for dmntk-feel-temporal
    cmds:
      - cmd: ./coverage.sh dmntk-feel-temporal

  cov-model:
    desc: Runs code coverage using grcov for dmntk-model
    cmds:
      - cmd: ./coverage.sh dmntk-model

  cov-recognizer:
    desc: Runs code coverage using grcov for dmntk-recognizer
    cmds:
      - cmd: ./coverage.sh dmntk-recognizer

  doc:
    desc: Generates documentation
    cmds:
      - cmd: cargo +stable doc --no-deps

  doc-open:
    desc: Generates documentation and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open

  doc-priv:
    desc: Generates documentation with private items
    cmds:
      - cmd: cargo +stable doc --no-deps --document-private-items

  doc-priv-open:
    desc: Generates documentation with private items and opens it in browser
    cmds:
      - cmd: cargo +stable doc --no-deps --open --document-private-items

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo +nightly fmt

  install:
    desc: Builds and installs release version
    cmds:
      - cmd: cargo +stable install dmntk --path dmntk --force

  musl:
    desc: Builds the Linux MUSL target
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-musl

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo clean
      - cmd: cargo +stable build --release

  run:
    desc: Runs the server in release mode
    cmds:
      - cmd: cargo +stable run --release -- srv

  run-musl:
    desc: Runs the server in release mode and musl target
    cmds:
      - cmd: cargo +stable run --release --target=x86_64-unknown-linux-musl -- srv

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo +nightly test --workspace

  testq:
    desc: Runs tests in debug and quiet mode
    cmds:
      - cmd: cargo +nightly test --workspace -q
