[package]
name = "dmntk-examples"
version = "0.0.43-dev"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
description = "DMNTK | Examples"
documentation = "https://docs.rs/dmntk-examples"
repository = "https://github.com/dmntk/dmntk.rs.git"
license = "MIT OR Apache-2.0"
edition = "2021"