[package]
name = "dmntk-examples"
version.workspace = true
authors.workspace = true
description = "DMNTK | Examples"
documentation = "https://docs.rs/dmntk-examples"
repository = "https://github.com/dmntk/dmntk.rs.git"
license = "MIT OR Apache-2.0"
edition = "2021"