[package]
name = "dmntk-feel-number"
version = "0.0.47-dev"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
description = "DMNTK | FEEL number"
documentation = "https://docs.rs/dmntk-feel-number"
repository = "https://github.com/dmntk/dmntk.rs.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dmntk-common = { path = "../common" }
dec-number-sys = { version = "0.0.22", optional = true }
dfp-number-sys = { version = "0.0.3", optional = true }

[features]
default = ["dec"]
dec = ["dec-number-sys"]
dfp = ["dfp-number-sys"]