[package]
name = "dmntk-feel"
version = "0.0.47-dev"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
description = "DMNTK | FEEL definitions"
documentation = "https://docs.rs/dmntk-feel"
repository = "https://github.com/dmntk/dmntk.rs.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
ascii_tree = "0.1.1"
chrono = "0.4.22"
chrono-tz = "0.6.3"
dmntk-common = { path = "../common" }
dmntk-feel-number = { path = "../feel-number" }
lazy_static = "1.4.0"
regex = "1.6.0"