[package]
name = "dmntk-workspace"
version = "0.0.40"
authors = ["Dariusz Depta <dariusz.depta@dmntk.io>"]
description = "DMNTK | Workspace"
documentation = "https://docs.rs/dmntk-workspace"
repository = "https://github.com/dmntk/dmntk.rs.git"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
dmntk-common = "0.0.40"
dmntk-evaluator = "0.0.40"
dmntk-feel = "0.0.40"
dmntk-model = "0.0.40"
thiserror = "1.0.30"
